import type { Room } from "./contracts";

// Fictional room records. Coordinates illustrate neighborhoods, not real listings.
const images = [
  "/rooms/studio.jpg",
  "/rooms/apartment.jpg",
  "/rooms/bright-room.jpg",
];
const rows: [
  string,
  string,
  string,
  number,
  number,
  number,
  number,
  Room["amenities"],
  string,
][] = [
  [
    "Studio ngập nắng, có ban công",
    "Nguyễn Gia Trí",
    "Bình Thạnh",
    10.8031,
    106.7143,
    4200000,
    28,
    ["aircon", "furnished", "balcony", "parking"],
    "Không gian sáng",
  ],
  [
    "Căn phòng nhỏ, đủ đầy tiện nghi",
    "Võ Oanh",
    "Bình Thạnh",
    10.8003,
    106.7148,
    3500000,
    22,
    ["aircon", "furnished", "parking"],
    "Giá dễ chịu",
  ],
  [
    "Studio hiện đại bên cửa sổ lớn",
    "Điện Biên Phủ",
    "Bình Thạnh",
    10.7974,
    106.7095,
    5100000,
    32,
    ["aircon", "furnished", "balcony"],
    "Nội thất đầy đủ",
  ],
  [
    "Phòng riêng yên tĩnh, gần công viên",
    "Phan Văn Trị",
    "Bình Thạnh",
    10.8127,
    106.6936,
    2900000,
    20,
    ["parking"],
    "Gần công viên",
  ],
  [
    "Gác lửng thoáng mát cho hai người",
    "Bạch Đằng",
    "Bình Thạnh",
    10.8053,
    106.7012,
    3800000,
    27,
    ["aircon", "parking"],
    "Có gác lửng",
  ],
  [
    "Studio tối giản giữa lòng thành phố",
    "Nguyễn Thị Minh Khai",
    "Quận 1",
    10.7899,
    106.7026,
    6500000,
    35,
    ["aircon", "furnished", "balcony", "parking"],
    "Vị trí trung tâm",
  ],
  [
    "Một góc xanh tại Tân Định",
    "Trần Khắc Chân",
    "Quận 1",
    10.7955,
    106.6932,
    4800000,
    28,
    ["aircon", "balcony", "parking"],
    "Ban công xanh",
  ],
  [
    "Phòng sáng, đi lại thuận tiện",
    "Nguyễn Đình Chiểu",
    "Quận 3",
    10.7787,
    106.6879,
    4500000,
    25,
    ["aircon", "furnished", "parking"],
    "Thuận tiện di chuyển",
  ],
  [
    "Studio có bếp và ban công riêng",
    "Võ Thị Sáu",
    "Quận 3",
    10.7885,
    106.6878,
    5800000,
    36,
    ["aircon", "furnished", "balcony", "parking"],
    "Bếp riêng",
  ],
  [
    "Không gian ấm cúng trên đường Lê Văn Sỹ",
    "Lê Văn Sỹ",
    "Quận 3",
    10.7897,
    106.6774,
    3900000,
    24,
    ["aircon", "furnished"],
    "Nội thất gọn gàng",
  ],
  [
    "Phòng thoáng gần khu đại học",
    "Tô Hiến Thành",
    "Quận 10",
    10.7782,
    106.6634,
    3200000,
    23,
    ["aircon", "parking"],
    "Gần trường học",
  ],
  [
    "Studio rộng rãi tại Quận 10",
    "Thành Thái",
    "Quận 10",
    10.7719,
    106.6671,
    4600000,
    30,
    ["aircon", "furnished", "balcony", "parking"],
    "Diện tích rộng",
  ],
  [
    "Phòng riêng cho người thích yên tĩnh",
    "Sư Vạn Hạnh",
    "Quận 10",
    10.768,
    106.6695,
    2800000,
    18,
    ["parking"],
    "Ngân sách tiết kiệm",
  ],
  [
    "Căn phòng có góc làm việc riêng",
    "Phan Xích Long",
    "Phú Nhuận",
    10.8003,
    106.6869,
    4300000,
    26,
    ["aircon", "furnished", "balcony"],
    "Góc làm việc",
  ],
  [
    "Studio nhiều ánh sáng tự nhiên",
    "Hoàng Văn Thụ",
    "Phú Nhuận",
    10.8018,
    106.6734,
    3700000,
    25,
    ["aircon", "furnished", "parking"],
    "Cửa sổ lớn",
  ],
  [
    "Phòng có gác, giờ giấc tự do",
    "Nguyễn Văn Trỗi",
    "Phú Nhuận",
    10.7991,
    106.6781,
    3100000,
    22,
    ["aircon", "parking"],
    "Giờ giấc tự do",
  ],
  [
    "Studio tiện nghi gần sân bay",
    "Cộng Hòa",
    "Tân Bình",
    10.8068,
    106.6545,
    4100000,
    28,
    ["aircon", "furnished", "parking"],
    "Kết nối thuận tiện",
  ],
  [
    "Phòng rộng với ban công riêng",
    "Hoàng Hoa Thám",
    "Tân Bình",
    10.8001,
    106.6446,
    3600000,
    29,
    ["aircon", "balcony", "parking"],
    "Ban công riêng",
  ],
];

export function seedRooms(): Room[] {
  return rows.map((row, index) => ({
    id: `room-${String(index + 1).padStart(2, "0")}`,
    code: `TH-HCM-${String(index + 1).padStart(5, "0")}`,
    title: row[0],
    street: row[1],
    district: row[2],
    lat: row[3],
    lng: row[4],
    price: row[5],
    area: row[6],
    amenities: row[7],
    highlight: row[8],
    image: images[index % images.length],
    imageAlt: "Ảnh nội thất minh họa, không phải ảnh của phòng thực tế",
    status: "AVAILABLE",
    version: 1,
  }));
}
